[build]
  functions = "functions"  # Folder where your functions will be stored
  publish = "public"  # The directory to publish to Netlify

[dev]
  functions = "functions"  # Path to the functions during local dev
  publish = "public"  # The directory for the dev environment
