[build]
  functions = "netlify/functions"  # Path to where your functions are stored
  publish = "public"               # Directory where your static files (HTML, CSS, JS) are stored

[dev]
  functions = "netlify/functions"  # During local dev, Netlify should look here for functions
  publish = "public"               # Directory for static assets in local dev
