[build]
  command = "npm install && echo 'Installing yt-dlp...' && npm run install-yt-dlp && npm run build-site"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
